program BuildEnt64;

uses
  Forms,
  ppClass in 'ppClass.pas', 
  ppProd in 'ppProd.pas', 
  ppClasUt in 'ppClasUt.pas', 
  ppReport in 'ppReport.pas', 
  ppBands in 'ppBands.pas',
  ppCtrls in 'ppCtrls.pas', 
  ppTypes in 'ppTypes.pas',
  ppUtils in 'ppUtils.pas', 
  ppPrintr in 'ppPrintr.pas', 
  ppDB in 'ppDB.pas', 
  ppDBPipe in 'ppDBPipe.pas', 
  ppDBBDE in 'ppDBBDE.pas', 
  ppRegion in 'ppRegion.pas', 
  ppStrtch in 'ppStrtch.pas', 
  ppViewr in 'ppViewr.pas', 
  ppMemo in 'ppMemo.pas',
  ppSubRpt in 'ppSubRpt.pas', 
  ppTmplat in 'ppTmplat.pas', 
  ppTmDlg in 'ppTmDlg.pas', 
  ppTxPipe in 'ppTxPipe.pas', 
  ppArchiv in 'ppArchiv.pas', 
  ppDBArchiv in 'ppDBArchiv.pas', 
  ppBarCod in 'ppBarCod.pas', 
  ppBarCode2D in 'ppBarCode2D.pas', 
  ppDBJIT in 'ppDBJIT.pas',
  ppDsIntf in 'ppDsIntf.pas', 
  ppDsgner in 'ppDsgner.pas', 
  ppFldEd in 'ppFldEd.pas', 
  ppEndUsr in 'ppEndUsr.pas', 
  ppVar in 'ppVar.pas', 
  ppRptExp in 'ppRptExp.pas', 
  ppRptExpCommon in 'ppRptExpCommon.pas', 
  ppDsgnDB in 'ppDsgnDB.pas',
  ppCTMain in 'ppCTMain.pas', 
  ppCTDlg in 'ppCTDlg.pas', 
  ppRichTx in 'ppRichTx.pas', 
  ppAsField in 'ppAsField.pas', 
  ppDBStorageSettings in 'ppDBStorageSettings.pas', 
  ppPreviewFormSettings in 'ppPreviewFormSettings.pas', 
  ppForms in 'ppForms.pas',
  ppParameter in 'ppParameter.pas', 
  ppParametersEd in 'ppParametersEd.pas',
  ppPageBreak in 'ppPageBreak.pas',  
  ppEmailSettings in 'ppEmailSettings.pas', 
  ppToolResources in 'ppToolResources.pas',
  myChkBox in 'myChkBox.pas',
  myChkBoxDesign in 'myChkBoxDesign.pas',
  daIDE in '..\DADE\daIDE.pas',
  daDatMan in '..\DADE\daDatMan.pas',
  daDatMod in '..\DADE\daDatMod.pas',
  daDataVw in '..\DADE\daDataVw.pas',
  daQClass in '..\DADE\daQClass.pas',
  daQuery in '..\DADE\daQuery.pas',
  raIDE in '..\RAP\raIDE.pas',
  raCodMod in '..\RAP\raCodMod.pas',
  ppSMTPOutlook in 'ppSMTPOutlook.pas',
  ppSMTPIndy10 in 'ppSMTPIndy10.pas',
  ppWinExtendedMAPI in 'ppWinExtendedMAPI.pas',
  ppExtendedMAPI in 'ppExtendedMAPI.pas',
  ppSMTPExtendedMAPI in 'ppSMTPExtendedMAPI.pas',
  ppPCL in 'ppPCL.pas',
  ppSMTPThunderbird in 'ppSMTPThunderbird.pas',
  ppJPEG in 'ppJPEG.pas',
  ppGIF in 'ppGIF.pas',
  ppPNG in 'ppPNG.pas',
  ppRESTMailGmail in 'ppRESTMailGmail.pas',
  ppRESTMailOutlook365 in 'ppRESTMailOutlook365.pas';

{$R *.RES}

begin
  Application.Run;
end.
